### ISSUE TITLE
doesnt work on ubuntu 20.04

### ISSUE THREAD

**Issue by Jimbolino** [pidario/rdm-build#1]
```
~/Applications$ ./rdm_7122488cc8aeabf83375920ef5970335.AppImage 
/tmp/.mount_rdm_71HFAR9a/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_rdm_71HFAR9a/usr/bin/../lib/libpython3.9.so.1.0)
/tmp/.mount_rdm_71HFAR9a/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_rdm_71HFAR9a/usr/bin/../lib/libsystemd.so.0)

```

**Comment by pidario** [comment]
It looks like appimage doesn't bundle all the needed libraries: <https://github.com/AppImage/pkg2appimage/blob/master/excludelist>
libc.so.6 is in the list for some reason.
Do you have the package `glibc` installed?

**Comment by Jimbolino** [comment]
i think ubuntu cannot run without glibc:
```
root@ubuntu20:~# dpkg --list | grep libc6
ii  libc6:amd64                          2.31-0ubuntu9.1                   amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                      2.31-0ubuntu9.1                   amd64        GNU C Library: Development Libraries and Header Files
```
```
root@ubuntu18:~$ dpkg --list | grep libc6
ii  libc6:amd64                          2.27-3ubuntu1.4                                 amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                      2.27-3ubuntu1.4                                 amd64        GNU C Library: Development Libraries and Header Files
ii  libc6-i386                           2.27-3ubuntu1.4                                 amd64        GNU C Library: 32-bit shared libraries for AMD64
```
maybe the newest ubuntu comes with 2.32, but most people are on a LTS release

**Comment by pidario** [comment]
That's right, I'm not familiar with Ubuntu (I use Arch btw :)) but I should've known. I'll try bundling libc too and I'll let you know.

**Comment by pidario** [comment]
Bundling libc is not a solution: I get this error

```
/tmp/appimage_extracted_79a203b551562580316795aff8bbcb82/AppRun.wrapped: symbol lookup error: /tmp/appimage_extracted_79a203b551562580316795aff8bbcb82/usr/bin/../lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
```
Anyway, since I don't have an Ubuntu machine I've been trying using `ubuntu:20.04` image from docker hub which might not be the ideal environment for X applications (even though I used to run poedit just fine in a container).
I guess I'll try using a VM.

**Comment by pidario** [comment]
Well, I tried to statically link glibc (which, as I understand, is considered a bad practice) but unfortunately it didn't work.
I then went through the AppImage documentation site and I stumbled on [this](https://docs.appimage.org/reference/best-practices.html). It looks like the best results come from building the AppImage on an older distribution such as Centos 7. I also tried that but I couldn't find a way to install properly all Qt modules (I got everything except for Qt charts), so I couldn't start the build process.
After the Centos incident, I tried patching the build configuration file as suggested in [Glibc version header generator ](https://github.com/wheybags/glibc_version_header). Building was fine and I clearly saw that `g++` used the new header but the resulting binary still wasn't working in ubuntu 20.04.
Any idea here will be appreciated.

**Comment by pidario** [comment]
I finally managed to get it to build on a `centos 7` container. For arch users nothing should change. I tested on a ubuntu 20.04 virtualbox and it worked but the log window was showing a bunch of errors (probably related to formatters, so if you don't use them you can ignore them). I guess one improvement at a time!
Can you try the new appimage and let me know?

**Comment by Jimbolino** [comment]
Thnx for the effort, but unfortunately it cannot get it to work.

```
$ chmod +x rdm.AppImage 
$ ./rdm.AppImage 

(AppImageLauncher:28906): GLib-CRITICAL **: 04:23:26.214: g_file_test: assertion 'filename != NULL' failed
Enable auto-scaling
TLS support: "OpenSSL 1.1.1f  31 Mar 2020"
App font: "Open Sans" 11
Values font: "Ubuntu Mono"
("en-US")
Detected locale: "en_US"
Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr/local'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr/local'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/local/lib/python39.zip',
    '/usr/local/lib/python3.9',
    '/usr/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f598d62e240 (most recent call first):
<no Python frame>

$ python3 --version
Python 3.8.5
```

I've tried installing python 3.9 from a ppa: https://linuxize.com/post/how-to-install-python-3-9-on-ubuntu-20-04/
but then it gives me the following error:
```
(AppImageLauncher:30930): GLib-CRITICAL **: 04:26:42.184: g_file_test: assertion 'filename != NULL' failed
Enable auto-scaling
TLS support: "OpenSSL 1.1.1f  31 Mar 2020"
App font: "Open Sans" 11
Values font: "Ubuntu Mono"
("en-US")
Detected locale: "en_US"
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.9/site.py", line 79, in <module>
    import os
  File "/usr/lib/python3.9/os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "/usr/lib/python3.9/_collections_abc.py", line 416, in <module>
    class _CallableGenericAlias(GenericAlias):
TypeError: type 'types.GenericAlias' is not an acceptable base type
```

**Comment by pidario** [comment]
Apologies, I forgot one minor but important detail: you have to run it like this:
`PYTHONHOME=/usr/lib/python3.8 PYTHONPATH=/usr/lib/python3.8:$PYTHONPATH ./rdm.AppImage`
You don't need to install python 3.9 since it's already bundled in the appimage, but you have to point PYTHONHOME to your python installation directory. In my virtualbox test, ubuntu 20.04 had python 3.8 installed but yours may vary.
I also got it to run without setting PYTHONHOME, just PYTHONPATH:
`PYTHONPATH=/usr/lib/python3.8:$PYTHONPATH ./rdm.AppImage`

Since you went through the hassle of installing python 3.9 you may want to use that directory instead but I didn't test it.

**Comment by Jimbolino** [comment]
yes this works:
`PYTHONPATH=/usr/lib/python3.8 ./rdm.AppImage`

if python is included in the app image, shouldnt it point to a path inside the image?

**Comment by pidario** [comment]
No, I believe it is a path of your host. Besides, what's bundled is just libpython3.9.so.1.0 but if I'm not mistaken what the appimage complains is missing is the python standard library which is not contained in the appimage. I tried to add it also inside the bundle but I got the same error i was telling you about.
Just speculating here, I'm not familiar at all with python ecosystem.

**Comment by boniek83** [comment]
Doesn't work on Fedora 34:
```
$ PYTHONHOME=/usr/lib/python3.9 PYTHONPATH=/usr/lib/python3.9 ./rdm.AppImage
Enable auto-scaling
TLS support: "OpenSSL 1.1.1k  FIPS 25 Mar 2021"
App font: "Open Sans" 11
Values font: "Ubuntu Mono"
("en-GB")
Detected locale: "en_GB"
Python path configuration:
  PYTHONHOME = '/usr/lib/python3.9'
  PYTHONPATH = '/usr/lib/python3.9'
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr/lib/python3.9'
  sys.base_exec_prefix = '/usr/lib/python3.9'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr/lib/python3.9'
  sys.exec_prefix = '/usr/lib/python3.9'
  sys.path = [
    '/usr/lib/python3.9',
    '/usr/lib/python3.9/lib/python39.zip',
    '/usr/lib/python3.9/lib/python3.9',
    '/usr/lib/python3.9/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f85d85788c0 (most recent call first):
<no Python frame>

```

**Comment by Jimbolino** [comment]
just wanted to say thank you, and confirm that everything works on ubuntu 22.04 :)
(recently deleted all my snaps, so came back to your project)

**Comment by pidario** [comment]
Good to hear that 22.04 solved the issue :)
